INSERT INTO filme(nome,genero,ator,diretor)VALUES('Inatividade Paranormal','Comedia','Marlon Wayans','Micahel Tiddes');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Gente Grande','Comedia','Adam Sandler','Dennis Dugan');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Gente Grande 2','Comedia','Adam Sandler','Dennis Dugan');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Maze Runner','Sci-Fi','Dylan O Brien','Wes Ball');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Maze Runner 2','Sci-Fi','Dylan O Brien','Wes Ball');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Maze Runner 3','Sci-Fi','Dylan O Brien','Wes Ball');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Panico na Floresta','Horror','Eliza Dushku','Rob Schmidt');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('O Massacre da Serra Eletrica','Horror','Gunnar Hansen','Tobe Hooper');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Titanic','Romance','Leonardo DiCaprio','James Cameron');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Minha Vida em Marte','Romance','Paulo Gustavo','Susana Garcia');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Arranha Ceu-coragem Sem Limites','Acao','Dwayne Johnnson','Rawson Marshall Thurber');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('A Morte Te Da Parabens','Thriller','Jessica Rothe','Christopher B. Landon');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('A Morte Te Da Parabens 2','Thriller','Jessica Rothe','Christopher B. Landon');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Extraordinario','Drama','Jacob Tremblay','Stephen Chbosky');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Uncharted Out Of The Map','Misterio','Tom Holland','Ruben Fleischer');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Dupla Implacavel','Policial','John Travolta','Pierre Morel');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Shrek','Animacao','Mike Myers','Andrew Adamson');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Shrek 2','Animacao','Mike Myers','Andrew Adamson');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Indiana Jones e os Caçadores da Arca Perdida','Aventura','Harrison Ford','James Mangold');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Indiana Jones e o Reino da Caveira de Cristal','Aventura','Harrison Ford','James Mangold');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('As Cronicas de Spiderwick','Fantasia','Freddie Highmore','Mark Waters');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('A Verdade Nua e Crua','Comedia Romantica','Gerald Butler','Robert Luketic');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Bad Boys','Acao Comedia','Will Smith, Martin Lawrence','Michael Bay');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Bad Boys 2','Acao Comedia','Will Smith, Martin Lawrence','Michael Bay');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('Spawn','Super Heroi','Michael Jai White','Mark Dippé');
INSERT INTO filme(nome,genero,ator,diretor)VALUES('O Incrivel Hulk','Sci-Fi','Edward Norton','Louis Leterrier');